### ISSUE TITLE
Does this work deal with the workload balance when scheduing?

### ISSUE THREAD

**Issue by darrenglow** [datadreamer-dev/DataDreamer#17]

**Comment by AjayP13** [comment]
I assume you're talking about this:
https://github.com/vllm-project/vllm/issues/1237#issuecomment-2017239455

But yes, it does balance the work between multiple instances of the vLLM model.

**Comment by darrenglow** [comment]
Yes, I am trying to do dataparallel using vLLM based on your project. 
I have read the guide, but still feel confused about how to do this. I wonder if there is any specific doc or example?

**Comment by AjayP13** [comment]
You can see this test case right here (`test_parallel_llm`) for some example code:

https://github.com/datadreamer-dev/DataDreamer/blob/ad3dd9ce73e8ad66f3c1b124686ea970e347343a/src/tests/trainers/test_distributed.py#L131

That test case will run a two copies of an LLM (one per GPU on a 2-GPU machine) using Hugging Face Transformers.

If you want to use `VLLM` instead of `HFTransformers` instead, it's as simple as:

```python3
from datadreamer.llms import VLLM
llm_1 = VLLM("gpt2", device=0)
llm_2 = VLLM("gpt2", device=0)
```

**Comment by darrenglow** [comment]
wow this is so easy to use. It helps me a lot. Thanks for your fantastic work.

**Comment by AjayP13** [comment]
No problem, let me know if you need any other help!
