### ISSUE TITLE
Question about the speed

### ISSUE THREAD

**Issue by darrenglow** [datadreamer-dev/DataDreamer#19]
I run two vLLM instances on 2 A100-40G to do inference. However, I found that the throughput is less than 2 times of the vLLM on one card. 
I am not sure whether the batch matters. As in vLLM, it uses the continuous batching, but datadreamer seems to do inference in batches.

**Comment by AjayP13** [comment]
How exactly are you testing it? Can you share your test code? DataDreamer is made for batched inference over a dataset, so it should be fast, it's not really made for API serving. With 2 GPUs I would expect it to be faster than a single GPU and but slightly slower than a single GPU twice due to overhead. I would create 500 prompts. Run them on 1 GPU and test the speed. Then create 500 prompts run them on two GPUs to test the speed.

**Comment by darrenglow** [comment]
Sorry for the late response. I tested it again and found that I changed somewhere wrongly in the source file. When I pip install again, the speed seems reasonable. yes, the throughput on two cards is slightly slower than a single GPU twice, which is acceptable.
