### ISSUE TITLE
error while using HFAPIEndpoint

### ISSUE THREAD

**Issue by ronysalem** [datadreamer-dev/DataDreamer#28]
when i am using HFAPIEndpoint
i am getting several errors

1. when the model i used is gated and eventhough the provided huggingface token granted access i am getting that the mdel is resticted 
2. WHen i use any other model that didn't need access i am getting this error 
[ 🧠 HFAPIEndpoint (https://api-inference.huggingface.co/)] Retrying HFAPIEndpoint.run in 3.0 seconds as it raised JSONDecodeError: Expecting value: line 1 column 1 (char 0).

**Comment by AjayP13** [comment]
Not enough information to debug. We do test this, you can see an example here:

https://github.com/datadreamer-dev/DataDreamer/blob/c535dc4482906e5886e2d4009edd64d306e5dd4e/src/tests/llms/test_llms.py#L2300

If you want you can further debug and propose a PR if something is wrong, otherwise I believe this is working.
